[versions]
sykepengerGradlePlugins = "20261001.1830"

[libraries]
flyway-postgresql = "org.flywaydb:flyway-database-postgresql:13.8.1"
hikariCP = "com.zaxxer:HikariCP:7.1.0"
kotliquery = "com.github.seratch:kotliquery:1.9.1"
postgresql = "org.postgresql:postgresql:42.7.13"

rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026091610031789545782"

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
