[versions]
sykepengerGradlePlugins = "20261001.1830"

[libraries]
flyway-postgresql = "org.flywaydb:flyway-database-postgresql:11.5.0"
hikariCP = "com.zaxxer:HikariCP:7.1.0"
kotliquery = "com.github.seratch:kotliquery:1.9.0"
postgresql = "org.postgresql:postgresql:42.7.7"

rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026011411051768385145.e8ebad1177b4"

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
