name: Bygg og deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: test and build
        run: ./gradlew build
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        cluster:
          - dev-gcp
          - prod-gcp
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: .nais/app.yml
          VARS: .nais/${{ matrix.cluster }}.yml
          IMAGE: ${{ needs.build.outputs.image }}